### ISSUE TITLE
How to set $WORKON_HOME on windows

### ISSUE THREAD

**Issue by xuehao** [jorgenschaefer/pyvenv#32] opened 2015-06-18 05:06 UTC

**Comment by jorgenschaefer** [comment] 2015-06-18 05:48
Hello, and thank you for the question! I do not use Windows, so have no idea, but does this page help?
https://virtualenvwrapper.readthedocs.org/en/latest/install.html#windows-command-prompt

**Comment by jorgenschaefer** [comment] 2015-08-22 14:40
Lacking any further updates on this, I assume the problem is solved and I will close this issue. Please do not hesitate to open a new one if you have any further problems!

**Closed by jorgenschaefer** 2015-08-22 14:40 UTC
Labels: question
